import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Bus, Package, LogOut, Plus, Search, RefreshCw, Edit, CreditCard } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import type { Database } from "@/integrations/supabase/types";
import MpesaPaymentDialog from "@/components/MpesaPaymentDialog";

type Parcel = Database["public"]["Tables"]["parcels"]["Row"];
type ParcelStatus = Database["public"]["Enums"]["parcel_status"];
type BusOperator = Database["public"]["Enums"]["bus_operator"];

const statusColors: Record<ParcelStatus, string> = {
  pending: "bg-yellow-100 text-yellow-800 border-yellow-200",
  received: "bg-blue-100 text-blue-800 border-blue-200",
  in_transit: "bg-purple-100 text-purple-800 border-purple-200",
  delivered: "bg-green-100 text-green-800 border-green-200",
  cancelled: "bg-red-100 text-red-800 border-red-200",
};

const Admin = () => {
  const { user, isAdmin, loading, signOut } = useAuth();
  const navigate = useNavigate();
  const { toast } = useToast();
  const [parcels, setParcels] = useState<Parcel[]>([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [editingParcel, setEditingParcel] = useState<Parcel | null>(null);
  const [paymentParcel, setPaymentParcel] = useState<{ id: string; trackingId: string; amount: number } | null>(null);
  useEffect(() => {
    if (!loading && !user) {
      navigate("/auth");
    }
  }, [user, loading, navigate]);

  const fetchParcels = async () => {
    setIsLoading(true);
    const { data, error } = await supabase
      .from("parcels")
      .select("*")
      .order("created_at", { ascending: false });

    if (error) {
      toast({
        title: "Error loading parcels",
        description: error.message,
        variant: "destructive",
      });
    } else {
      setParcels(data || []);
    }
    setIsLoading(false);
  };

  useEffect(() => {
    if (user) {
      fetchParcels();
    }
  }, [user]);

  const handleCreateParcel = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);

    const newParcel: Database["public"]["Tables"]["parcels"]["Insert"] = {
      tracking_id: "", // Auto-generated by database trigger
      sender_name: formData.get("senderName") as string,
      sender_phone: formData.get("senderPhone") as string,
      sender_address: formData.get("senderAddress") as string,
      receiver_name: formData.get("receiverName") as string,
      receiver_phone: formData.get("receiverPhone") as string,
      receiver_address: formData.get("receiverAddress") as string,
      origin_city: formData.get("originCity") as string,
      destination_city: formData.get("destinationCity") as string,
      weight: parseFloat(formData.get("weight") as string),
      bus_operator: formData.get("busOperator") as BusOperator,
      notes: (formData.get("notes") as string) || null,
      sender_user_id: user?.id ?? null,
    };

    const weight = parseFloat(formData.get("weight") as string);
    const paymentAmount = 200 + weight * 50; // KES 200 base + KES 50/kg

    const { data, error } = await supabase.from("parcels").insert({
      ...newParcel,
      payment_amount: paymentAmount,
    }).select().single();

    if (error) {
      toast({
        title: "Error creating parcel",
        description: error.message,
        variant: "destructive",
      });
    } else if (data) {
      toast({
        title: "Parcel created",
        description: "Now proceed to payment.",
      });
      setIsCreateOpen(false);
      setPaymentParcel({
        id: data.id,
        trackingId: data.tracking_id,
        amount: paymentAmount,
      });
      fetchParcels();
    }
  };

  const handleUpdateStatus = async (parcelId: string, newStatus: ParcelStatus) => {
    const { error } = await supabase
      .from("parcels")
      .update({ status: newStatus })
      .eq("id", parcelId);

    if (error) {
      toast({
        title: "Error updating status",
        description: error.message,
        variant: "destructive",
      });
    } else {
      toast({
        title: "Status updated",
        description: `Parcel status changed to ${newStatus}.`,
      });
      fetchParcels();
    }
  };

  const filteredParcels = parcels.filter(
    (parcel) =>
      parcel.tracking_id.toLowerCase().includes(searchTerm.toLowerCase()) ||
      parcel.sender_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      parcel.receiver_name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <RefreshCw className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="bg-card border-b border-border">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center">
              <Bus className="w-5 h-5 text-primary-foreground" />
            </div>
            <div>
              <h1 className="font-display font-bold text-xl text-foreground">BusParcel Admin</h1>
              <p className="text-sm text-muted-foreground">{user?.email}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {isAdmin && (
              <Badge variant="secondary" className="bg-accent text-accent-foreground">
                Admin
              </Badge>
            )}
            <Button variant="ghost" size="icon" onClick={() => navigate("/")}>
              <Package className="w-5 h-5" />
            </Button>
            <Button variant="ghost" size="icon" onClick={signOut}>
              <LogOut className="w-5 h-5" />
            </Button>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8">
        {/* Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
          <Card>
            <CardHeader className="pb-2">
              <CardDescription>Total Parcels</CardDescription>
              <CardTitle className="text-3xl">{parcels.length}</CardTitle>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardDescription>In Transit</CardDescription>
              <CardTitle className="text-3xl text-purple-600">
                {parcels.filter((p) => p.status === "in_transit").length}
              </CardTitle>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardDescription>Delivered</CardDescription>
              <CardTitle className="text-3xl text-green-600">
                {parcels.filter((p) => p.status === "delivered").length}
              </CardTitle>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardDescription>Pending</CardDescription>
              <CardTitle className="text-3xl text-yellow-600">
                {parcels.filter((p) => p.status === "pending").length}
              </CardTitle>
            </CardHeader>
          </Card>
        </div>

        {/* Actions Bar */}
        <div className="flex flex-col sm:flex-row gap-4 mb-6">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              placeholder="Search by tracking ID, sender, or receiver..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10"
            />
          </div>
          <Button onClick={fetchParcels} variant="outline">
            <RefreshCw className="w-4 h-4" />
            Refresh
          </Button>
          <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
            <DialogTrigger asChild>
              <Button>
                <Plus className="w-4 h-4" />
                New Parcel
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle>Create New Parcel</DialogTitle>
                <DialogDescription>
                  Fill in the details to register a new parcel for shipment.
                </DialogDescription>
              </DialogHeader>
              <form onSubmit={handleCreateParcel} className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-4">
                    <h3 className="font-semibold text-foreground">Sender Details</h3>
                    <div className="space-y-2">
                      <Label htmlFor="senderName">Name</Label>
                      <Input id="senderName" name="senderName" required />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="senderPhone">Phone</Label>
                      <Input id="senderPhone" name="senderPhone" required />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="senderAddress">Address</Label>
                      <Input id="senderAddress" name="senderAddress" required />
                    </div>
                  </div>
                  <div className="space-y-4">
                    <h3 className="font-semibold text-foreground">Receiver Details</h3>
                    <div className="space-y-2">
                      <Label htmlFor="receiverName">Name</Label>
                      <Input id="receiverName" name="receiverName" required />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="receiverPhone">Phone</Label>
                      <Input id="receiverPhone" name="receiverPhone" required />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="receiverAddress">Address</Label>
                      <Input id="receiverAddress" name="receiverAddress" required />
                    </div>
                  </div>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="originCity">Origin City</Label>
                    <Input id="originCity" name="originCity" placeholder="e.g., Nairobi" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="destinationCity">Destination City</Label>
                    <Input id="destinationCity" name="destinationCity" placeholder="e.g., Mombasa" required />
                  </div>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="weight">Weight (kg)</Label>
                    <Input id="weight" name="weight" type="number" step="0.1" min="0.1" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="busOperator">Bus Operator</Label>
                    <Select name="busOperator" required>
                      <SelectTrigger>
                        <SelectValue placeholder="Select operator" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="tahmeed">Tahmeed</SelectItem>
                        <SelectItem value="buscar">Buscar</SelectItem>
                        <SelectItem value="mashpoa">Mashpoa</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="notes">Notes (optional)</Label>
                  <Textarea id="notes" name="notes" placeholder="Any special instructions..." />
                </div>
                <Button type="submit" className="w-full">
                  Create Parcel
                </Button>
              </form>
            </DialogContent>
          </Dialog>
        </div>

        {/* Parcels Table */}
        <Card>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Tracking ID</TableHead>
                  <TableHead>Sender</TableHead>
                  <TableHead>Receiver</TableHead>
                  <TableHead>Route</TableHead>
                  <TableHead>Operator</TableHead>
                   <TableHead>Status</TableHead>
                   <TableHead>Payment</TableHead>
                   <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {isLoading ? (
                  <TableRow>
                    <TableCell colSpan={8} className="text-center py-8">
                      <RefreshCw className="w-6 h-6 animate-spin mx-auto text-muted-foreground" />
                    </TableCell>
                  </TableRow>
                ) : filteredParcels.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={8} className="text-center py-8 text-muted-foreground">
                      No parcels found
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredParcels.map((parcel) => (
                    <TableRow key={parcel.id}>
                      <TableCell className="font-mono font-medium">{parcel.tracking_id}</TableCell>
                      <TableCell>
                        <div>
                          <p className="font-medium">{parcel.sender_name}</p>
                          <p className="text-sm text-muted-foreground">{parcel.sender_phone}</p>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div>
                          <p className="font-medium">{parcel.receiver_name}</p>
                          <p className="text-sm text-muted-foreground">{parcel.receiver_phone}</p>
                        </div>
                      </TableCell>
                      <TableCell>
                        {parcel.origin_city} → {parcel.destination_city}
                      </TableCell>
                      <TableCell className="capitalize">{parcel.bus_operator}</TableCell>
                      <TableCell>
                        <Badge className={statusColors[parcel.status]} variant="outline">
                          {parcel.status.replace("_", " ")}
                        </Badge>
                       </TableCell>
                       <TableCell>
                         {(parcel as any).payment_status === "paid" ? (
                           <Badge className="bg-green-100 text-green-800 border-green-200" variant="outline">
                             Paid
                           </Badge>
                         ) : (parcel as any).payment_status === "pending" ? (
                           <Badge className="bg-yellow-100 text-yellow-800 border-yellow-200" variant="outline">
                             Pending
                           </Badge>
                         ) : (
                           <Button
                             size="sm"
                             variant="outline"
                             onClick={() =>
                               setPaymentParcel({
                                 id: parcel.id,
                                 trackingId: parcel.tracking_id,
                                 amount: (parcel as any).payment_amount || 200 + parcel.weight * 50,
                               })
                             }
                           >
                             <CreditCard className="w-3 h-3 mr-1" />
                             Pay
                           </Button>
                         )}
                       </TableCell>
                       <TableCell>
                        <Select
                          value={parcel.status}
                          onValueChange={(value) => handleUpdateStatus(parcel.id, value as ParcelStatus)}
                        >
                          <SelectTrigger className="w-32">
                            <Edit className="w-3 h-3 mr-1" />
                            <span className="text-xs">Update</span>
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="pending">Pending</SelectItem>
                            <SelectItem value="received">Received</SelectItem>
                            <SelectItem value="in_transit">In Transit</SelectItem>
                            <SelectItem value="delivered">Delivered</SelectItem>
                            <SelectItem value="cancelled">Cancelled</SelectItem>
                          </SelectContent>
                        </Select>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </main>

      {paymentParcel && (
        <MpesaPaymentDialog
          open={!!paymentParcel}
          onOpenChange={(open) => !open && setPaymentParcel(null)}
          parcelId={paymentParcel.id}
          trackingId={paymentParcel.trackingId}
          amount={paymentParcel.amount}
          onPaymentInitiated={fetchParcels}
        />
      )}
    </div>
  );
};

export default Admin;
